name: CI/CD DEV Pipeline

on:
  push:
    branches:
        - 'feature/**'
        # - '!master'   # excludes master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to DEV instance
        env:
          KEY: ${{ secrets.GCP_DEV_KEY }}
          HOST: ${{ secrets.GCP_DEV_HOST }}
          USER: ${{ secrets.GCP_DEV_USER }}
        run: |
          # SETUP SSH KEY IN GIT ACTIONS RUNNER ENV
          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/dev_key
          chmod 600 ~/.ssh/dev_key
          ssh-keyscan $HOST >> ~/.ssh/known_hosts
