name: CI/CD DEV Pipeline

on:
  push:
    branches:
        - 'feature/**'
        # - '!master'   # excludes master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to GCE Instance
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GCP_DEV_KEY }}
        HOST: ${{ secrets.GCP_DEV_HOST }}
        USER: ${{ secrets.GCP_DEV_USER }}
      run: |
        # Setup SSH key in the GitHub Actions runner environment
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/dev_key
        chmod 600 ~/.ssh/dev_key
        ssh-keyscan $HOST >> ~/.ssh/known_hosts

        # SSH into the GCE instance and execute deployment commands
        ssh -i ~/.ssh/dev_key $USER@$HOST << 'ENDSSH'
          # Commands to run on the GCE instance
          # These should be the steps to deploy your application
          # Example:
          cd /var/www/html/misfit-mutt
          git pull
          # Any other deployment commands
        ENDSSH
